### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by ksm200** [TheDoctor0/CSGOMod#28] opened 2020-08-24 00:20 UTC
logs
L 08/23/2020 - 17:36:42: [CS:GO StratTrak] SQL Error: Table 'contas_csgo.csgo_stattrak' doesn't exist (1146)

and chance all max caracteres menus

missing menuData characters [128] change for [555] all :)
![image](https://user-images.githubusercontent.com/64114407/90999763-ddadc300-e59d-11ea-827d-1173b192b3f3.png)

**Comment by TheDoctor0** [comment] 2020-08-24 08:22
> L 08/23/2020 - 17:36:42: [CS:GO StratTrak] SQL Error: Table 'contas_csgo.csgo_stattrak' doesn't exist (1146)

Huh, that is weird. I deleted this table on my test server and after map change it has been recreated without a problem.
I added error logging for queries in sql_init functions, so if there is some problem with that it should show in logs.

> and chance all max caracteres menus
missing menuData characters [128] change for [555] all :)

Length of strings in some menus have been greatly increased. You can check it now 👍

**Comment by TheDoctor0** [comment] 2020-08-24 09:00
Question unrelated to this issue, how long will it take you to finish brazilian portuguese translation?
I would gladly include it in next minor release.

**Comment by ksm200** [comment] 2020-08-24 15:01
am I finishing as a phaco to send you later?

**Comment by TheDoctor0** [comment] 2020-08-24 15:26
Sure, you can send whole csgomod.txt to my email (it's visible on my profile).

**Comment by ksm200** [comment] 2020-08-24 17:53
L 08/24/2020 - 14:51:48: [CS:GO StatTrak] Init SQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0), `weapon_scout` int(10) NOT NULL DEFAULT(0), `weapon_xm1014` int(10) NOT NUL' at line 1

**Comment by TheDoctor0** [comment] 2020-08-24 18:37
Hmm... that's weird. `queryData[2048]` should be more than enough for this query, but it seems truncated for you.
I even checked it on my server and works fine.
Does it work with [this change](https://github.com/TheDoctor0/CSGOMod/commit/61dddf41d7cda549586a9acb5615d8493157c867)?

**Comment by ksm200** [comment] 2020-08-24 18:39
I will test

**Comment by TheDoctor0** [comment] 2020-08-24 19:56
I looked at your previous comment and noticed that syntax error is caused by `DEFAULT (0)` which seems to not work on your MySQL/MariaDB server version. I [changed it](https://github.com/TheDoctor0/CSGOMod/blob/6f5c723e43e042d78170cc2cf568fbbe86e26814/cstrike/addons/amxmodx/scripting/csgo_stattrak.sma#L174) to universal `DEFAULT 0` syntax so it should be fixed.

**Comment by ksm200** [comment] 2020-08-24 20:31
fix thanks

**Closed** 2020-08-24 21:07 UTC
Labels: bug
