### ISSUE TITLE
physics error on maps fy_

### ISSUE THREAD

**Issue by tenlimba** [TheDoctor0/CSGOMod#90] opened 2020-11-13 16:56 UTC
The physics plugin remove the gun on maps type fy / he / awp etc..

**Comment by TheDoctor0** [comment] 2020-11-14 09:56
Just tested it and it doesn't seem to be the case:

![20201114104226_1](https://user-images.githubusercontent.com/16612504/99144528-dd860680-2666-11eb-94d7-6fef0285ad6a.jpg)

**Comment by tenlimba** [comment] 2020-11-14 10:56
On my server, it deletes them from the floor if they are not thrown by someone

**Comment by TheDoctor0** [comment] 2020-11-14 11:00
Please provide console output for those commands:
- version
- meta version
- meta list
- amxx version
- amxx plugins

Also, I advise using [BasePack](https://github.com/AMXX-pl/BasePack).

**Comment by tenlimba** [comment] 2020-11-14 11:02
version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.696-dev
Build date: 18:46:47 May 18 2020 (2228)
Build from: https://github.com/dreamstalker/rehlds/commit/987ee51

meta version
Metamod v1.21p38 2018/02/11 (5:13)
by Will Day
http://www.metamod.org/
Patch: Metamod-P (mm-p) v38
by Jussi Kivilinna
http://metamod-p.sourceforge.net/
compiled: Feb 11 2018, 11:05:06 EET (optimized)

meta list
Currently loaded plugins:
descriptionstat pend file verssrcload unlod
[ 1] Reunion RUN- reunion_mm_i386. v0.1.0.9 iniStart Never
[ 2] AMX Mod X RUN- amxmodx_mm_i386. v1.8.3-d iniStart ANY
[ 3] ReAuthCheckRUN- reauthcheck_mm_i v0.1.6 iniStart Never
[ 4] hackdetector RUN- hackdetector_amx v0.15.32 iniANYANY
[ 5] Ultimate Unprec RUN- unprecacher_i386 vBeta 2. iniChlvl Chlvl
[ 6] POD-Bot mm RUN- podbot_mm_i386.s vV3B22 iniChlvl ANY
[ 7] LinHL-Booster RUN- booster_mm_i386. v1.20 iniChlvl Pause
[ 8] MySQRUN- mysql_amxx_i386. v1.8.3-d pl2ANYANY
[ 9] SQLite RUN- sqlite_amxx_i386 v1.8.3-d pl2ANYANY
[10] Fun RUN- fun_amxx_i386.so v1.8.3-d pl2ANYANY
[11] Engine RUN- engine_amxx_i386 v1.8.3-d pl2ANYANY
[12] FakeMetaRUN- fakemeta_amxx_i3 v1.8.3-d pl2ANYANY
[13] GeoIPRUN- geoip_amxx_i386. v1.2.0-m pl2ANYANY
[14] Ham Sandwich RUN- hamsandwich_amxx v1.8.3-d pl2ANYANY
[15] CStrike RUN- cstrike_amxx_i38 v1.8.2 pl2ANYANY
15 plugins, 15 running

amxx version
AMX Mod X 1.8.3-dev+5201 (http://www.amxmodx.org)
Authors:
David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Sep 1 2018 09:52:22
Built from: https://github.com/alliedmodders/amxmodx/commit/8c0f97d
Build ID: 5201:8c0f97d
Core mode: JIT+ASM32

amxx plugins
Currently loaded plugins:
name version authorfile status
[ 1] Pret Admine - HUD 1.0UspStyLe preturi.amxx running
[ 2] VIP System [OPRIT]1.0YONTU donatori.amxx stopped
[ 3] VIP Clasic 1.6Shadows Adi vip.amxxrunning
[ 4] AMX_M_VIP2.0MrPower vip_model.amxxrunning
[ 5] Admin Groups1.2OciXCrom crx_admingroups running
[ 6] Game Messages & Sounds 3.0OciXCrom crx_gamemessage running
[ 7] Achievements2.0!Pastout!! Achievements_v2 running
[ 8] CSGO Grafiti Plugin 2.0Fatih ~ EjderYaCSGO_Graffiti_P running
[ 9] C4 Taker 1.10 hellmonja & Haml c4_taker.amxx running
[ 10] unknown unknown unknown unlag.amxx running
[ 11] DHUD Team Details 0.1.7 Askhanar team_score.amxx running
[ 12] Admin Base 1.8.3-dev+ AMXX Dev Team admin.amxx running
[ 13] Admin Base (SQL) 1.8.3-dev+ AMXX Dev Team admin_sql.amxxrunning
[ 14] Admin Commands 1.8.3-dev+ AMXX Dev Team admincmd.amxx running
[ 15] Admin Help 1.8.3-dev+ AMXX Dev Team adminhelp.amxxrunning
[ 16] Slots Reservation 1.8.3-dev+ AMXX Dev Team adminslots.amxx running
[ 17] Multi-Lingual System 1.8.3-dev+ AMXX Dev Team multilingual.am running
[ 18] Menus Front-End1.8.3-dev+ AMXX Dev Team menufront.amxxrunning
[ 19] Commands Menu 1.8.3-dev+ AMXX Dev Team cmdmenu.amxx running
[ 20] Players Menu1.8.3-dev+ AMXX Dev Team plmenu_ab_base. running
[ 21] Maps Menu1.8.3-dev+ AMXX Dev Team mapsmenu.amxx running
[ 22] Plugin Menu 1.8.3-dev+ AMXX Dev Team pluginmenu.amxx running
[ 23] OciXCrom's Admin Chat3.1OciXCrom adminchat.amxxrunning
[ 24] Anti Flood 1.8.3-dev+ AMXX Dev Team antiflood.amxxrunning
[ 25] Scrolling Message 1.8.3-dev+ AMXX Dev Team scrollmsg.amxxrunning
[ 26] Info. Messages 1.8.3-dev+ AMXX Dev Team imessage.amxx running
[ 27] Admin Votes 1.8.3-dev+ AMXX Dev Team adminvote.amxxrunning
[ 28] Galileo v5.9.1-926 Brad Jones/Addon galileo.amxx running
[ 29] Pause Plugins 1.8.3-dev+ AMXX Dev Team pausecfg.amxx running
[ 30] Stats Configuration 1.8.3-dev+ AMXX Dev Team statscfg.amxx running
[ 31] Ultimate Stats 1.3O'Zoneultimate_stats. debug
[ 32] Auto Center Msg1.0Rusu mesaj.amxx running
[ 33] unknown unknown unknown CONNECT.amxx running
[ 34] Advanced Mute 2.1OciXCrom crx_advmute.amx running
[ 35] You Are Dead! 1.0OciXCrom crx_youdead.amx running
[ 36] Limbaj Admini 1.0Ex3cuTioNlimbaj_admini.a running
[ 37] csgo tinta 2.4csfweed tintav2.amxx running
[ 38] AMXX Parachute 1.0H.RED.ZONE parasuta.amxx running
[ 39] WarGods Cerere 1.0DanN wg.amxx running
[ 40] Round Sounds Advanced1.2CryWolf round_sounds_ad running
[ 41] Reset Score 1.0Silenttt resetscore.amxx running
[ 42] Autoresponder/Advertis 0.5MaximusBroodad_manager.amxx running
[ 43] Ultimate Fire in the H 2.1OciXCrom crx_fireintheho running
[ 44] Sprite Damage 1.0Liesprite_damage_r running
[ 45] Instant AutoTeamBalanc 0.3.0 ConnorMcLeodinstant_autotea running
[ 46] plugin_comenzi 1.0Rusu comenzi.amxx running
[ 47] No Team Flash 0.2KRoTano_team_flash.a running
[ 48] Amx PM1.3Sonic pm.amxx running
[ 49] Activitate Admini 1.2.1 rewr Askhanar activitate_admi running
[ 50] Chat Logger 2.1a Jimchat_logger.amx running
[ 51] Admin Spectator ESP 1.3KoST admin_spec_esp. running
[ 52] Realistic FlashBang 1.0.1 GlaDiuS Realistic_Flash running
[ 53] Exploding Gernade 1.0P34nutgrenaderealism. running
[ 54] MultiJump1.1twistedeuphoriamultijump.amxxrunning
[ 55] c4 timer 1.1cheap_suit c4timer.amxx running
[ 56] ComboSprites0.5Chrescoe1combo_sprtes.am running
[ 57] AMXX Russian2.2.0 CryWolf amx_pika.amxx running
[ 58] Vampire 1.0c Shalfey hp.amxx running
[ 59] POD-Bot Menu1.3g4s|figurE.09 amxx_podbotmenu running
[ 60] [CS] Player Models API 1.2WiLS cs_player_model running
[ 61] CSO Costumes3.9Smilex_Gamercostumes.amxx running
[ 62] Ammo From Kill 0.1Exolent refill.amxxrunning
[ 63] Auto Join on Connect 0.1VENauto_join_on_co running
[ 64] Chat Manager4.5.1 OciXCrom crx_chatmanager running
[ 65] CM: Toggle Chat4.1OciXCrom crx_chatmanager running
[ 66] Advanced Screen Shot 1.1GhosT ***amx_ss.amxxrunning
[ 67] FUCKOFF 2.Translat Un_Dylau amxx_fuckoff.am running
[ 68] Camera Changer 1.1XunTric camera.amxxrunning
[ 69] [TM] Old Precache 0.1P.Of.Pw tut_precache.am running
[ 70] Tutor Messages Shower2.0P.Of.Pw tutor_msg_showe running
[ 71] Fast Knife 1.0OciXCrom crx_fast_knife. running
[ 72] Quick and No Scope Det 1.2EFFx QuickNoScopeD.a running
[ 73] [SCM] Entity Editor 1.3.1 schmurgel1983 scm_entity_edit running
[ 74] [CS] Team Semiclip3.3.1 schmurgel1983 cs_team_semicli running
[ 75] CS:GO Mod Core 2.2.1 O'Zonecsgo_core.amxxrunning
[ 76] CS:GO Clans 2.2.1 O'Zonecsgo_clans.amxx running
[ 77] CS:GO Accounts 2.2.1 O'Zonecsgo_accounts.a running
[ 78] CS:GO Nades 2.2.1 O'Zonecsgo_nades.amxx running
[ 79] CS:GO VIP and SVIP2.2.1 O'Zonecsgo_vip_svip.a running
[ 80] CS:GO Server Menu 2.2.1 O'Zonecsgo_server_men running
[ 81] CS:GO Transfer 2.2.1 O'Zonecsgo_transfer.a running
[ 82] CS:GO Operations 2.2.1 O'Zonecsgo_operations running
[ 83] CS:GO Molotov 2.2.1 DynamicBits & O' csgo_molotov.am running
[ 84] CS:GO Smoke 2.2.1 Numb & O'Zone csgo_smoke.amxx running
[ 85] CS:GO Zeus 2.2.1 wopox1337 & O'Zo csgo_zeus.amxxrunning
[ 86] CS:GO Run Boost2.2.1 O'Zonecsgo_runboost.a running
[ 87] CS:GO Inspect 2.2.1 O'Zonecsgo_inspect.am running
[ 88] CS:GO Buy Menu 2.2.1 O'Zonecsgo_buymenu.am running
[ 89] CS:GO Rank System 2.2.1 O'Zonecsgo_ranks.amxx running
[ 90] CS:GO Assist and Reven 2.2.1 O'Zonecsgo_assist_rev running
[ 91] CS:GO StatTrak 2.2.1 O'Zonecsgo_stattrak.a running
[ 92] CS:GO No Distractions2.2.1 O'Zonecsgo_no_distrac running
[ 93] CS:GO Weapon Physics 2.2.1 O'Zone & Nomexou csgo_physics.am running
[ 94] Admin AutoBhop 2.2.1 ConnorMcLeodsvip_bhop.amxxrunning
94 plugins, 93 running

**Comment by TheDoctor0** [comment] 2020-11-14 11:10
It seems like you have mismatched module versions:
`[15] CStrike RUN- cstrike_amxx_i38 v1.8.2 pl 2 ANY ANY`

To be honest, your 1.8.3 build version is pretty old.
Please upgrade AMXX to 1.9.0 and then check if the issue is still present.
As I said, I advise using [BasePack](https://github.com/AMXX-pl/BasePack).

You also have a lot of custom plugins and any of them may cause some issues.

This is definitely not a problem with CS:GO mod itself, so I'm closing this issue.

**Closed by TheDoctor0** 2020-11-14 11:10 UTC
