### ISSUE TITLE
The bullets leave numbers on the walls

### ISSUE THREAD

**Issue by tenlimba** [TheDoctor0/CSGOMod#99] opened 2020-12-26 16:06 UTC
When you shoot at the walls, some numbers remain.
https://imgur.com/S7RQvTu
https://imgur.com/dCGyMUy

**Comment by TheDoctor0** [comment] 2020-12-27 16:06
Just tested this by shooting more than 100 bullets at the wall and I cannot confirm such issue.
![20201227170452_1](https://user-images.githubusercontent.com/16612504/103174851-cccfcf80-4865-11eb-9d62-7c139cab58c7.jpg)

**Comment by tenlimba** [comment] 2020-12-27 17:11
In plugins i have:
preturi.amxx
donatori.amxx
vip.amxx
;vip_model.amxx
crx_admingroups.amxx
;crx_ranksystem.amxx
Achievements_v2.0.amxx
CSGO_Graffiti_Plugin_Fix.amxx
c4_taker.amxx
unlag.amxx
team_score.amxx
;csr_gundrop.amxx
WinTeam_Sprite.amxx
PrecacheX.amxx

; AMX Mod X plugins

; Admin Base - Always one has to be activated
admin.amxx		; admin base (required for any admin-related)
admin_sql.amxx		; admin base - SQL version (comment admin.amxx)

; Basic
admincmd.amxx		; basic admin console commands
adminhelp.amxx		; help command for admin console commands
adminslots.amxx		; slot reservation
multilingual.amxx	; Multi-Lingual management

; Menus
menufront.amxx		; front-end for admin menus
cmdmenu.amxx		; command menu (speech, settings)
plmenu_ab_base.amxx		; players menu (kick, ban, client cmds.)
;telemenu.amxx		; teleport menu (Fun Module required!)
mapsmenu.amxx		; maps menu (vote, changelevel)
pluginmenu.amxx		; Menus for commands/cvars organized by plugin

; Chat / Messages
adminchat.amxx		; console chat commands
antiflood.amxx		; prevent clients from chat-flooding the server
scrollmsg.amxx		; displays a scrolling message
imessage.amxx		; displays information messages
adminvote.amxx		; vote commands

; Map related
;nextmap.amxx		; displays next map in mapcycle
;mapchooser.amxx		; allows to vote for next map
;timeleft.amxx		; displays time left on map
galileo.amxx
;dmc233.amxx

; Configuration
pausecfg.amxx		; allows to pause and unpause some plugins
statscfg.amxx		; allows to manage stats plugins via menu and commands

; Counter-Strike
;restmenu.amxx		; restrict weapons menu
;statsx.amxx		; stats on death or round end (CSX Module required!)
;miscstats.amxx		; bunch of events announcement for Counter-Strike
;stats_logging.amxx	; weapons stats logging (CSX Module required!)
ultimate_stats.amxx debug

; Enable to use AMX Mod plugins
;amxmod_compat.amxx	; AMX Mod backwards compatibility layer

;Sarbatori
mesaj_sarbatori.amxx
;Craciun
;amx_fireworks.amxx
;AIO_Winter.amxx
;Paste.amxx
;Halloween.amxx

; Custom - Add 3rd party plugins here

;mesaj.amxx
CONNECT.amxx
gag.amxx
crx_youdead.amxx
limbaj_admini.amxx
tintav2.amxx
parasuta.amxx
wg.amxx
round_sounds_advanced.amxx
resetscore.amxx
ad_manager.amxx
crx_fireinthehole.amxx
;sprite_damage_randomcolorV2.amxx
instant_autoteambalance_nocrash.amxx
comenzi.amxx
no_team_flash.amxx
pm.amxx
activitate_admini.amxx
chat_logger.amxx
admin_spec_esp.amxx
Realistic_FlashBang.amxx
grenaderealism.amxx
multijump.amxx
sillyc4.amxx
c4timer.amxx
amx_pika.amxx
hp.amxx
;cs_player_models_api.amxx
;costumes.amxx
refill.amxx
team_join.amxx
crx_chatmanager.amxx
crx_chatmanager_toggle.amxx
amx_ss.amxx
amxx_fuckoff.amxx
camera.amxx
crx_fast_knife.amxx
QuickNoScopeD.amxx
Owner_Connected.amxx
realnadedrops.amxx

In plugins_csgo i have:
; CS:GO Mod
csgo_core.amxx               ; main plugin
csgo_clans.amxx              ; clans system
csgo_accounts.amxx           ; account system
csgo_nades.amxx              ; nades models and short / medium throw
csgo_vip_svip.amxx           ; vip (flag 't') and supervip (flag 'x')
csgo_server_menu.amxx        ; main server menu ('v' key and /menu command)
csgo_transfer.amxx           ; money transfer
csgo_operations.amxx         ; operations system
csgo_molotov.amxx            ; cs:go molotov
csgo_smoke.amxx              ; cs:go smoke
csgo_zeus.amxx               ; cs:go zeus
csgo_runboost.amxx           ; run boost
csgo_inspect.amxx            ; weapon inspect
csgo_buymenu.amxx            ; new buy menu
csgo_ranks.amxx              ; ranks system
csgo_assist_revenge.amxx     ; assists and revenge
csgo_stattrak.amxx           ; stattrak for every weapon
csgo_no_distractions.amxx    ; remove shield, nightvision and loud fans
csgo_physics.amxx            ; physics for weapons
svip_bhop.amxx
CS1.6Bet.com.amxx

and i have teamsemiclip.

And the rehlds is your base rehlds.
And I don't know why they appear.

**Comment by TheDoctor0** [comment] 2020-12-27 19:53
Try disabling all plugins not included by default in AMXX or CS:GO mod.
If there will be no longer such an issue then it is caused by one of those disabled plugins.

**Comment by TheDoctor0** [comment] 2020-12-30 18:01
@tenlimba, have you checked it?

**Comment by tenlimba** [comment] 2020-12-30 18:07
I haven't tried anything yet because I was busy with work but tomorrow I try being free

**Comment by tenlimba** [comment] 2020-12-31 07:31
I tried and those numbers still appear.

But I updated to cs go mod 2.4.0 and these errors appear when someone connects and restarts their server:

> warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/fun_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/fun_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/f9/c14f7091980c9040f83a165d9e8a25fc230d5e.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/engine_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/engine_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/bf/18ff595d4ecbf0a6cf20f00a49ae195b2e2591.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/fakemeta_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/fakemeta_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/e1/9524dbc37d2f3ae579415cba1ddf3523e8fda5.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/geoip_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/geoip_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/03/cdc3d4088d995e8a39c1d4922377b927e9303c.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/nvault_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/nvault_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/60/b7848c24eac2d8698992e79fc5f1fc7a397933.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/hamsandwich_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/hamsandwich_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/ea/34c0113041b61b6e844a5eb89c0def6eb295d7.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/csx_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/csx_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/dd/c16d19a711dddc78172aaac5579ec8a7410c54.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/cstrike_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/cstrike_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/17/2891ee7797621a62490e42a6c7c9bb6e051963.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/sockets_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/sockets_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/17/e5e8df8a2f66a995effb74ff5109b8599f962f.debug

warning: Ignoring non-absolute filename: <cstrike/addons/amxmodx/modules/regex_amxx_i386.so>
Missing separate debuginfo for cstrike/addons/amxmodx/modules/regex_amxx_i386.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/6b/b374d49eeba1e9ae385071ef168e3446e179b5.debug
email debug.log to linux@valvesoftware.com
Thu Dec 31 09:25:12 EET 2020: Server restart in 10 seconds

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/home/client9984/.steam/sdk32/steamclient.so
with error:
/home/client9984/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 10:14:22 Aug 19 2020 (2321)
STEAM Auth Server
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
Usage:
Setmaster unavailable, start a server first.
"fps_max" is "999"
Server IP address 93.114.82.47:27015

Metamod-r version 1.3.0.128 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `meta gpl' for details.

Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:48 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70

AMX Mod X version 1.10.0.5406 Copyright (c) 2004-2015 AMX Mod X Development Team
AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
This is free software and you are welcome to redistribute it under
certain conditions; type 'amxx gpl' for details.

12/31/2020 - 09:25:22: [GEOIP] Database info: GeoLite2 City database 2.0
=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=

LinHL-Booster v1.20 by hullu <hullu@hullu.cjb.net>

=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=+=-=
ReGameDL version: 5.18.0.475-dev
12/31/2020 - 09:25:22: -------- Mapchange to de_miez --------
12/31/2020 - 09:25:23: [csgo_core.amxx] CS:GO Mod by O'Zone (v2.4.0).
12/31/2020 - 09:25:23: [csgo_core.amxx] Loaded 140 skins from 140 files.
Precache X System: Model Precache Reserved Slots: 354
Precache X System: Sound Precache Reserved Slots: 303
[AMXX] Loaded 10 admins from file

Admin Spectator ESP v1.3, Copyright (C) 2006 by KoST

Executing AMX Mod X Configuration File
[AMXX] No admins found.
12/31/2020 - 09:25:25: [galileo.amxx]
12/31/2020 - 09:25:25: [galileo.amxx] The server is jumping to the next map after the current map due more than 1 restarts on the map "de_dust2"
12/31/2020 - 09:25:25: [galileo.amxx]
Client menu item 1 added to Client Menus Front-End: "SCM: Entity Editor" from plugin "[SCM] Entity Editor"
Executing Team Semiclip 3.3.1 Configuration File
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
/home/client9984/.steam/sdk32/steamclient.so
with error:
/home/client9984/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit

Connection to Steam servers successful.
VAC secure mode is activated.

**Comment by TheDoctor0** [comment] 2020-12-31 08:36
Those logs suggest that you have some kind of problem with AMXX modules.
Not even a single line includes anything related to cs:go mod.

**Comment by tenlimba** [comment] 2020-12-31 08:53
![20201231_105205](https://user-images.githubusercontent.com/70764621/103402760-5b8a6800-4b56-11eb-843d-ffc307ceb160.jpg)
Its here the problem

**Comment by TheDoctor0** [comment] 2020-12-31 09:09
I told you to disable all plugins beside default AMXX plugins and cs:go mod.
That custom hud suggests that you didn't do it.

**Comment by tenlimba** [comment] 2020-12-31 09:29
Only with base plugins + cs go mod
![20201231_112730](https://user-images.githubusercontent.com/70764621/103404200-64316d00-4b5b-11eb-9577-56ec2fcbdb24.jpg)
![20201231_112720](https://user-images.githubusercontent.com/70764621/103404205-68f62100-4b5b-11eb-9a39-950dd643b957.jpg)
![Uploading 20201231_112737.jpg…]()

**Comment by TheDoctor0** [comment] 2020-12-31 09:35
And without cs:go mod?

Also, those bullet holes do not look like default sprites. Are you using a non-steam cs 1.6 client?

**Comment by tenlimba** [comment] 2020-12-31 10:09
Yes only base plugins and cs go
Yes I use non steam but I have a friend who uses steam and he sees them too.

**Comment by TheDoctor0** [comment] 2020-12-31 10:18
In the previous comment I meant to check it with cs:go mod disabled - only AMXX.

Can you give me your server IP address?
I'd like to check if I would encounter this issue there because on my test server I cannot replicate it in any way.

**Comment by tenlimba** [comment] 2020-12-31 10:30
93.114.82.47:27015

**Comment by tenlimba** [comment] 2020-12-31 10:51
With only base  plugin and my plugins the number i don't see

**Comment by TheDoctor0** [comment] 2020-12-31 13:50
I don't know what you did on your server, but shot decals are clearly changed - check `decals.wad`.
I'm 100% sure that this is a problem with your server, so I'm closing this issue.

**Closed by TheDoctor0** 2020-12-31 13:50 UTC
Labels: minor bug
